package sec1;

public class ExceptionExam2 {

	public static void main(String[] args) {
		String name = null;
		//실제 처리할 문장(try)이 예외가 발생한면 , 예외처리 문장(catch)을 실행
		try {
			//실제 처리할 문장
			System.out.println(name.toString());
		} catch(NullPointerException e) {
			e.printStackTrace();
		} catch(Exception e) {
			System.out.println("정체불가 예외발생");
		} 

	}

}
